### PR TITLE
Remove redundant constraints

### PR DESCRIPTION
**Pull request by octover**
⚠️ 🔫 Xcode 9 catches and warns about these, removing them still builds in Xcode 8

### CODE REVIEW

**Comment by foadsaliba** [comment]
@octover is it ok to leave this until xcode 9 is released? which would be on tuesday probably?

**Comment by octover** [comment]
The GM is out, but it's fine to wait until the App Store version is out if you want. I just had some spare time on the train and thought I'd try and tackle some of the warnings. We've switched our Travis to Xcode 9 which is also running the GM.

I did check building with Xcode 8.3.3 so it should be backwards compatible and doesn't require building with Xcode 9.

**Comment by octover** [comment]
I actually accidentally submitted the PR upstream and it had a bunch of changes Claudio did that are in an open in another pull request. I would like to get this all upstream, but guessing the reason it is forked is since the original project seems like it isn’t being actively maintained anymore.

On Fri, 15 Sep 2017 at 16:51 Claudio

<
mailto:Claudio <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

@ccarnino

approved this pull request.

Looks good. Agree with Foad to just wait a bit.

Do we plan to contribute back with a PR on the original project?

—

You are receiving this because you were mentioned.

Reply to this email directly,
https://github.com/discovery-fusion/dkids_apple_spine/pull/1#pullrequestreview-63067772
, or

**Comment by foadsaliba** [comment]
thanks @octover !

**Pull request merged**
